name: ajleitch
favicon: null
layout_spectrum: 0.03312
typography_spectrum: 0.60209
title: 'A.J. Leitch: Photography | Motion | Design'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040000'
    - '#60798d'
    - '#fafdfc'
    - '#194549'
    - '#b55521'
  brandStrength: 0.625
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose: []
