name: ajleitch
favicon: null
layout_spectrum: 0.4070811446290463
typography_spectrum: 0.5770426564849913
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.3951413161121309
  lightness: 0.30455701937898993
  saturation: 0.15544212120585144
  rhythmicContrast: 0.4635040359571576
purpose: []
