name: ajleitch
favicon: null
layout_spectrum: 0.03312
typography_spectrum: 0.60209
title: 'A.J. Leitch: Photography | Motion | Design'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#aeaeae'
    - '#d1d1d1'
    - '#7f7f7f'
    - '#363636'
    - '#f8f8f8'
  brandStrength: 0.625
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0
purpose: []
