name: ajleitch
favicon: null
layout_spectrum: 0.31641
typography_spectrum: 0.60209
title: 'A.J. Leitch: Photography | Motion | Design'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#080808'
    - '#a6a39c'
    - '#feffff'
    - '#6c4838'
    - '#c9394f'
  brandStrength: 0.3125
  lightness: 0.3125
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
